# Add the current directory to the path Thor uses
# to look up files
def source_paths
  Array(super) +
    [File.expand_path(File.dirname(__FILE__))]
end

remove_file "Gemfile"
run "touch Gemfile"
add_source 'https://rubygems.org'
gem 'rails', '4.2.1'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'


gem_group :development, :test do
  gem 'rspec-rails', require: false
  gem 'byebug'
  gem 'web-console', '~> 2.0'
end

gem_group :test do
  gem 'simplecov', require: false
  gem 'simplecov-rcov', :require => false
end

gsub_file 'app/assets/javascripts/application.js', /\/\/= require turbolinks\n/, ''

remove_file ".gitignore"
create_file '.gitignore' do <<-EOF
# See https://help.github.com/articles/ignoring-files for more about ignoring files.
#
# If you find yourself ignoring temporary files generated by your text editor
# or operating system, you probably want to add a global ignore instead:
#   git config --global core.excludesfile '~/.gitignore_global'

# Ignore bundler config.
/.bundle

# Ignore local database.yml file
/config/database.yml

# Ignore all logfiles and tempfiles.
/log/*
!/log/.keep
/tmp

# Ignore editor config files
.idea

EOF
end

inside 'config' do
  remove_file 'database.yml'
  create_file 'database.yml.example' do <<-EOF
default: &default
  adapter: postgresql
  host: localhost
  timeout: 5000

development:
  <<: *default
  database: #{app_name}_development

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: #{app_name}_test

production:
  <<: *default
  database: #{app_name}_production

  EOF
  end
  run 'cp database.yml.example database.yml'
end



after_bundle do
  remove_dir "test"

    application do <<-RUBY
      config.generators do |g|
        g.test_framework :rspec, fixture: true
        g.view_specs false
        g.helper_specs false
      end
    RUBY
    end

  generate "rspec:install"

  rake "db:create"
  rake "db:migrate"

  git :init
  git add: "."
  git commit: "-a -m 'Initial commit'"
end